CompanyBlog/BlogPosts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):

    title = StringField('Title : ',validators=[DataRequired()])
    text = TextAreaField('Text : ', validators=[DataRequired()])
    submit= SubmitField('Post')

CompanyBlog/BlogPosts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint
from flask_login import current_user,login_required
from CompanyBlog import db
from CompanyBlog.models import BlogPost
from CompanyBlog.BlogPosts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)


#CREATE
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                            text=form.text.data,
                            user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Has Been Created Successfully!')

        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


#BLOG POST (VIEW)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date, post=blog_post)


#UPDATE
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data

        db.session.commit()
        flash('Blog Post Has Been Updated Successfully!')

        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    elif request.method == 'GET':

        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html',title='Updating',form=form)


#DELETE
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted!')

    return redirect(url_for('core.index'))

CompanyBlog/Core/views.py
# Core/views.py

from flask import render_template,request,Blueprint
from CompanyBlog.Users.views import account
from CompanyBlog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():

    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=8)

    return render_template('index.html',blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')

CompanyBlog/Users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from CompanyBlog import db
from CompanyBlog.models import User, BlogPost
from CompanyBlog.Users.forms import RegistrationForm, LoginForm, UpdateUserForm
from CompanyBlog.Users.pictureHandler import addProfilePic


users = Blueprint('users',__name__)



#Register
@users.route('/register',methods=['POST','GET'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():

        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks For Registeration!')

        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

#Login
@users.route('/login',methods=['POST','GET'])
def login():

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.checkPassword(form.password.data) and user is not None:
            print('User Found')
            login_user(user)
            flash('Login Successfully!')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


#Logout
@users.route('/logout')
def logout():
    logout_user()

    return redirect(url_for('core.index'))


#Account (Update User Form)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:

            username = current_user.username
            pic = addProfilePic(form.picture.data,username)
            current_user.profileImage = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated!')

        return redirect(url_for('users.account'))

    elif request.method == 'GET':

        form.username.data = current_user.username
        form.email.data = current_user.email

    profileImage = url_for('static', filename='profile_pics/' + current_user.profileImage)

    return render_template('account.html',profileImage=profileImage, form=form)


#User's List of Blog Posts
@users.route('/<username>')
def userPosts(username):

    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

CompanyBlog/templates/account.html
{% extends 'base.html' %}

{% block content %}

  <div class="jumbotron">
    <div align='center'>
        <h1>Welcome {{current_user.username}}</h1>
        <img src="{{url_for('static',filename='profile_pics/' + current_user.profileImage)}}" width="200px" height="200px">
    </div>
  </div>

  <form method="POST" action="" enctype="multipart/form-data">

    {{form.hidden_tag()}}

    <div class="form-group">
      {{ form.email.label }}
      {{ form.email(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.username.label }}
      {{ form.username(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.picture.label }}
      {{ form.picture(class='form-control-file') }}
      <small class="form-text text-muted"><span style="color:red">*</span>Only JPG & PNG File. Recommended Size Is 200*200 Pixels.</small>
    </div>

    <div class="form-group">
      {{ form.submit(class='btn btn-primary') }}
    </div>

  </form>
{% endblock %}

CompanyBlog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tech Form</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </head>
  <body>

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <li class="nav-link"> <a href="{{url_for('core.index')}}"> Home </a> </li>
      <li class="nav-link"> <a href="{{url_for('core.info')}}">About</a> </li>

      {% if current_user.is_authenticated %}

        <li class="nav-link"> <a href="{{url_for('users.logout')}}">Log Out</a> </li>
        <li class="nav-link"> <a href="{{url_for('users.account')}}">Account</a> </li>
        <li class="nav-link"> <a href="{{url_for('blog_posts.create_post')}}">Create Post</a> </li>

      {% else %}

        <li class="nav-link"> <a href="{{url_for('users.login')}}">Log In</a> </li>
        <li class="nav-link"> <a href="{{url_for('users.register')}}">Register</a> </li>

      {% endif %}

    </nav>


    <div class="container">
      {% block content %}

      {% endblock %}
    </div>


  </body>
</html>

CompanyBlog/templates/blog_post.html
{% extends 'base.html'%}

{% block content %}

  <div class="jumbotron">
    <h2>{{post.title}}</h2>
    <h4>Post By: {{post.author.username}}</h4>
    <p class="text-muted small">Published On: {{post.date.strftime('%d-%m-%Y')}}</p>
    <p>{{post.text}}</p>

    {% if post.author == current_user %}
      <div class="">
        <a class="btn btn-primary" href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
      </div>

    {% endif %}

  </div>

  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are You Sure You Want To Delete The Post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
          <input class="btn btn-danger" type="submit" name="" value="Confirm Delete">
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

CompanyBlog/templates/create_post.html
{% extends 'base.html'%}
{% block content %}

  <div class="container">
    <form class="form-group" method="POST">
      {{ form.hidden_tag() }}

      <div class="form-group">
        {{ form.title.label(class='form-control-label') }}
        {{ form.title(class='form-control form-control-lg')}}
      </div>

      <div class="form-group">
        {{ form.text.label(class='form-control-label')}}
        {{ form.text(class='form-control form-control-lg')}}
      </div>

      <div class="form-group">
        {{ form.submit(class='btn btn-outline-info')}}
      </div>

    </form>
  </div>

{% endblock %}

CompanyBlog/templates/index.html
{% extends 'base.html' %}
{% block content %}


  {% if current_user.is_authenticated %}
    <div class="jumbotron justify-content-center">
      <h1 class="display-4">Welcome To Tech Forum, {{current_user.username}}</h1>
    </div>
  {% else %}
    <div class="jumbotron ">
      <h1 class="display-4">Welcome To Tech Forum</h1>
    </div>
  {% endif %}


  <div class="container">
    {% for post in blog_posts.items %}

      <div class="card-body">
        <h2> <a class=card-title" "href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}} </a> </h2>
        <a href="{{ url_for('users.userPosts', username=post.author.username) }}">Post By: {{post.author.username}}</a>
        <p class="text-muted small">Published On : {{post.date.strftime('%d-%m-%Y')}}</p>
        <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read Blog Post</a>
      </div>
    {% endfor %}
  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}

        {% if blog_posts.page == page_num %}
        <!-- If error on user_post then user userPosts -->
          <li class="page-item disabled">
            <a class="page-link "href="{{url_for('core.index', page=page_num)}}">{{page_num}} </a>
          </li>

        {% else %}

          <li class="page-item">
            <a class="page-link "href="{{url_for('core.index', page=page_num)}}">{{page_num}} </a>
          </li>

        {% endif %}

      {% endfor %}

    </ul>
  </nav>


{% endblock %}

CompanyBlog/templates/info.html
{% extends 'base.html' %}
{% block content %}

  <div class="jumbotron">
      <h1 class="display-4">Info About Tech Forum</h1>
  </div>

  <article class="">

  </article>
{% endblock %}

CompanyBlog/templates/login.html
{% extends 'base.html'%}

{% block content%}

  <form method="POST">

    {{form.hidden_tag()}}

    <div class="form-group">
      {{ form.email.label }}
      {{ form.email(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.password.label }}
      {{ form.password(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.submit(class='btn btn-primary') }}
    </div>

  </form>

{% endblock %}

CompanyBlog/templates/register.html
{% extends 'base.html'%}

{% block content%}

  <form method="POST">

    {{form.hidden_tag()}}

    <div class="form-group">
      {{ form.email.label }}
      {{ form.email(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.username.label }}
      {{ form.username(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.password.label }}
      {{ form.password(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.pass_confirm.label }}
      {{ form.pass_confirm(class='form-control') }}
    </div>

    <div class="form-group">
      {{ form.submit(class='btn btn-primary') }}
    </div>

  </form>

{% endblock %}

CompanyBlog/templates/user_blog_posts.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    <div class="jumbotron">
        <div align='center'>
          <h1>Blog Posts Of {{user.username}}</h1>
          <img src="{{url_for('static',filename='profile_pics/' + user.profileImage)}}" >
        </div>
    </div>


    {% for post in blog_posts.items %}

      <h2> <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a> </h2>
      <!-- If error on user_post then user userPosts -->
      Post By : <a href="{{url_for('users.userPosts',username=post.author.username)}}">{{post.author.username}}</a> &nbsp;&nbsp;  
      <span class="text-muted small"> Published On: {{post.date.strftime('%d-%m-%Y')}}</span>
      <p>{{post.text}}</p>
      <br />

    {% endfor %}

  </div>


  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}

        {% if blog_posts.page == page_num %}
        <!-- If error on user_post then user userPosts -->
          <li class="page-item disabled">
            <a class="page-link "href="{{url_for('users.userPosts', username=user.username, page=page_num)}}">{{page_num}} </a>
          </li>

        {% else %}

          <li class="page-item">
            <a class="page-link "href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}} </a>
          </li>
        {% endif %}

      {% endfor %}

    </ul>
  </nav>

{% endblock %}